# Task-1

#### Creating a 3x3 matrix using numpy and multiplying each element with 3 and comparing with original matrix 

In [1]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = arr * 3
print(arr)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


# Task-2

#### Using pandas to create a DataFrame from a dictionary

In [5]:
import pandas as pd 
data = {
    'Product_Name' : ['Laptop','Mobile','Earphone'],
    'Price' : [150000,70000,15000],
    'Stock_quantity' : [40,100,90]
}
df = pd.DataFrame(data)
print(f"\nPandasDataFrame:\n{df}")


PandasDataFrame:
  Product_Name   Price  Stock_quantity
0       Laptop  150000              40
1       Mobile   70000             100
2     Earphone   15000              90


# Task-3

#### Using pandas to perform data filtering to find only and print products with more than 50 stocks

In [6]:
filtered_df = df[df['Stock_quantity'] > 50]
print(f"\nPandasDataFrame:\n{filtered_df}")


PandasDataFrame:
  Product_Name  Price  Stock_quantity
1       Mobile  70000             100
2     Earphone  15000              90
